// Shared branded email layouts. These are ONLY used by the server-side
// dev-only test endpoint. The real confirmation/recovery emails are rendered
// by Supabase Auth email templates pasted into the Supabase dashboard
// (see docs/email-templates.md) — same branding, Supabase-owned links.
const shell = (title, body) => `<!doctype html>
<html><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width" /></head>
<body style="margin:0;background:#f5f6fa;font-family:Inter,system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;">
  <div style="max-width:560px;margin:32px auto;background:#ffffff;border:1px solid #e5e7ef;border-radius:16px;overflow:hidden;">
    <div style="background:#5b4bf0;padding:24px 32px;color:#fff;">
      <div style="font-size:12px;letter-spacing:2px;opacity:.8;">CENTER</div>
      <div style="font-size:20px;font-weight:700;">Center Portal</div>
    </div>
    <div style="padding:32px;">
      <h2 style="margin:0 0 12px;color:#1c2033;">${title}</h2>
      ${body}
      <p style="margin-top:24px;font-size:12px;color:#6b7285;">If you did not request this email, you can safely ignore it.</p>
    </div>
  </div>
</body></html>`;

export const confirmationTemplate = (confirmUrl) => ({
  subject: "Confirm your Center Portal account",
  html: shell(
    "Welcome to Center Portal",
    `<p style="color:#1c2033;">Your account has been created successfully.</p>
     <p style="color:#1c2033;">Please confirm your email address to continue.</p>
     <p style="margin:24px 0;"><a href="${confirmUrl}" style="display:inline-block;background:#5b4bf0;color:#fff;text-decoration:none;padding:12px 28px;border-radius:8px;font-weight:600;">Confirm Email</a></p>
     <p style="font-size:12px;color:#6b7285;">Or paste this link into your browser:<br />${confirmUrl}</p>`
  ),
});

export const recoveryTemplate = (recoveryUrl) => ({
  subject: "Reset your Center Portal password",
  html: shell(
    "Reset your password",
    `<p style="color:#1c2033;">We received a request to reset your Center Portal password.</p>
     <p style="margin:24px 0;"><a href="${recoveryUrl}" style="display:inline-block;background:#5b4bf0;color:#fff;text-decoration:none;padding:12px 28px;border-radius:8px;font-weight:600;">Reset Password</a></p>
     <p style="font-size:12px;color:#6b7285;">Or paste this link into your browser:<br />${recoveryUrl}</p>`
  ),
});

export const testTemplate = () => ({
  subject: "Center Portal — Resend test email",
  html: shell(
    "Resend is connected",
    `<p style="color:#1c2033;">This test email was sent server-side through Resend.</p>
     <p style="color:#1c2033;">Production confirmation and password-reset emails are generated by Supabase Auth and delivered through Resend SMTP — this test only verifies the API key and sender.</p>`
  ),
});
