// POST /api/test-email  { "to": "you@example.com" }
// DEV-ONLY server-side check that RESEND_API_KEY + sender work.
// This does NOT replace Supabase Auth confirmation/recovery emails —
// those are generated by Supabase Auth and delivered via Resend SMTP.
import { getResend } from "../_lib/resendClient.js";
import { testTemplate } from "../_lib/emailTemplates.js";

const EMAIL_RE = /^\S+@\S+\.\S+$/;

export default async function handler(req, res) {
  if (process.env.NODE_ENV === "production" && process.env.ALLOW_TEST_EMAIL !== "true") {
    return res.status(403).json({ error: "Test endpoint is disabled in production." });
  }
  if (req.method !== "POST") {
    res.setHeader("Allow", "POST");
    return res.status(405).json({ error: "Method not allowed. Use POST." });
  }
  const to = String(req.body?.to ?? "").trim();
  if (!EMAIL_RE.test(to)) return res.status(400).json({ error: "A valid 'to' email is required." });

  let client;
  try {
    client = getResend();
  } catch (e) {
    return res.status(500).json({ error: "Resend is not configured on the server (RESEND_API_KEY missing)." });
  }
  const tpl = testTemplate();
  const { data, error } = await client.resend.emails.send({ from: client.from, to, ...tpl });
  if (error) {
    const msg = String(error.message || "").toLowerCase();
    if (msg.includes("testing emails") || msg.includes("verify a domain") || msg.includes("resend.dev")) {
      return res.status(400).json({
        error: "Resend test sender (onboarding@resend.dev) can only email your Resend signup address. Verify a domain in Resend, then set RESEND_FROM_EMAIL.",
      });
    }
    return res.status(502).json({ error: "Resend failed to send the test email. Check the API key and sender." });
  }
  return res.status(200).json({ ok: true, id: data?.id ?? null, from: client.from });
}
